# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml

logger:
  default: "info"
  logs:
    custom_components.adaptive_cover: debug

cover:
  - platform: template
    covers:
      vertical_blind:
        device_class: blind
        value_template: "{{is_state('input_boolean.test_service','on')}}"
        position_template: "{{states('input_number.cover_position')|int}}"
        set_cover_position:
          service: input_number.set_value
          data:
            entity_id: "input_number.cover_position"
            value: "{{position}}"
  - platform: template
    covers:
      tilt_blind:
        device_class: blind
        value_template: "{{is_state('input_boolean.test_service','on')}}"
        position_template: "{{states('input_number.cover_position_double_roller')|int}}"
        tilt_template: "{{states('input_number.cover_position_tilt')|int}}"
        set_cover_position:
          service: input_number.set_value
          data:
            entity_id: "input_number.cover_position_double_roller"
            value: "{{position}}"
        set_cover_tilt_position:
          service: input_number.set_value
          data:
            entity_id: "input_number.cover_position_tilt"
            value: "{{tilt}}"

input_number:
  cover_position:
    name: Cover Position
    min: 0
    max: 100
    step: 1
  cover_position_tilt:
    name: Cover Position Tilt
    min: 0
    max: 100
    step: 1
  cover_position_double_roller:
    name: Cover Position Double Roller
    min: 0
    max: 100
    step: 1

